# Generated by Django 5.2 on 2025-05-02 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('image', models.ImageField(upload_to='cars/')),
                ('distance_covered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('gear_type', models.CharField(choices=[('M', 'Manual'), ('A', 'Automatic'), ('H', 'Hybrid'), ('E', 'Electric')], max_length=1)),
            ],
        ),
    ]
